export const products = [
  {
    id: 1,
    name: "Laptop",
    price: 1500,
    description: "A high-performance laptop for all your needs.",
    photo: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600",
  },
  {
    id: 2,
    name: "Smartphone",
    price: 700,
    description: "A modern smartphone with an excellent camera.",
    photo: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600",
  },
  {
    id: 3,
    name: "Headphones",
    price: 200,
    description: "Noise-cancelling headphones for better focus.",
    photo: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
  },
  {
    id: 4,
    name: "Smartwatch",
    price: 350,
    description: "A stylish smartwatch with fitness tracking features.",
    photo: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
  },
  {
    id: 5,
    name: "Tablet",
    price: 900,
    description: "A lightweight tablet perfect for work and entertainment.",
    photo: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600",
  },
  {
    id: 6,
    name: "Camera",
    price: 1200,
    description: "A professional camera for stunning photography.",
    photo: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600",
  },
];

export const countries = [
  {
    name: "Австралія",
    capital: "Канберра",
    currency: "Австралійский доллар (AUD)",
    language: "Англійска",
    population: 24970200,
    flag: "https://flagcdn.com/w320/au.png",
    infected: false,
  },
  {
    name: "Болівія",
    capital: "Сукре",
    currency: "Болівіано (BOB)",
    language: "Іспанська, кечуа, аймара, гуарані",
    population: 10461053,
    flag: "https://flagcdn.com/w320/bo.png",
    infected: true,
  },
  {
    name: "Великобританія",
    capital: "Лондон",
    currency: "Фунт стерлінгів (GBP)",
    language: "Английска",
    population: 63395574,
    flag: "https://flagcdn.com/w320/gb.png",
    infected: false,
  },
  {
    name: "Ямайка",
    capital: "Кінгстон",
    currency: "Ямайский доллар (JMD)",
    language: "Англійська",
    population: 2868380,
    flag: "https://flagcdn.com/w320/jm.png",
    infected: false,
  },
  {
    name: "Швеція",
    capital: "Стокгольм",
    currency: "Шведська крона (SEK)",
    language: "Шведська",
    population: 9723809,
    flag: "https://flagcdn.com/w320/se.png",
    infected: true,
  },
  {
    name: "Португалія",
    capital: "Ліссабон",
    currency: "Евро (EUR)",
    language: "Португальска",
    population: 10799270,
    flag: "https://flagcdn.com/w320/pt.png",
    infected: true,
  },
];
